// massive-sprites - Plots and moves a lot of sprite images and polylines onto WebGL 2.5D surface.
// Copyright (c) Kouji Matsui. (@kekyo@mi.kekyo.net)
// Under MIT.
// https://github.com/kekyo/massive-sprites

// ==========================================================================================
// IMPORTANT NOTICE:
// Unified layout schema for command buffers and WASM.
// The order of these symbols is arranged based on code access within WASM, taking LoR into account.
// When adding or modifying elements, this must also be considered.
// ==========================================================================================

const commandOptionalFields = ['HAS', 'VALUE'];
const commandBorderMode = {
  KEEP: 0,
  CLEAR: 1,
  SET: 2,
};
const polylineCorrectionMode = {
  NONE: 0,
  FAN: 1,
};
const autoDirectionMode = {
  NONE: 0,
  ROTATION: 1,
  FLIPPING: 2,
};
const autoDirectionSpace = {
  WORLD: 0,
  PARENT_LOCAL: 1,
};

const commandValueFields = [
  'HAS',
  'VALUE',
  'HAS_INTERP',
  'KEEP_INTERP',
  'MODE',
  'DURATION',
  'EASING',
  'PARAM0',
  'PARAM1',
  'PARAM2',
  'PARAM3',
];

const commandRotationFields = [...commandValueFields];

const commandAutoDirectionFields = [
  'SPACE_HAS',
  'SPACE',
  'MODE_HAS',
  'MODE',
  'SHIFT_ANGLE_ROTATION_HAS',
  'SHIFT_ANGLE_ROTATION',
  'MIN_DISTANCE_HAS',
  'MIN_DISTANCE',
  'FLIP_X_HAS',
  'FLIP_X',
  'FLIP_Y_HAS',
  'FLIP_Y',
  'INTERP_HAS',
  'INTERP_CLEAR',
  'INTERP_MODE',
  'INTERP_DURATION',
  'INTERP_EASING',
  'INTERP_PARAM0',
  'INTERP_PARAM1',
  'INTERP_PARAM2',
  'INTERP_PARAM3',
];

const prefixFields = (prefix, fields) =>
  fields.map((field) => `${prefix}_${field}`);

const commandPolylineColorFields = [
  'COLOR0_R',
  'COLOR0_G',
  'COLOR0_B',
  'COLOR0_A',
  'COLOR1_R',
  'COLOR1_G',
  'COLOR1_B',
  'COLOR1_A',
  'REPEAT_LENGTH',
];

const commandPolylineJoinCorrectionFields = [
  'JOIN_CORRECTION_MODE',
  'JOIN_CORRECTION_INTERMEDIATE_POINT_COUNT',
];

const commandPolylineCapCorrectionFields = [
  'CAP_CORRECTION_MODE',
  'CAP_CORRECTION_POINT_COUNT',
];

const commandLeaderlineColorFields = commandPolylineColorFields.map(
  (field) => `LEADERLINE_${field}`
);

const commandBorderColorFields = ['COLOR_R', 'COLOR_G', 'COLOR_B', 'COLOR_A'];

const commandElementFields = [
  'KIND',
  'IMAGE_MODE',
  'TEX_INDEX',
  'ORIGIN_LOCATION_HAS',
  'ORIGIN_LOCATION_INDEX',
  'ORIGIN_LOCATION_USE_RESOLVED_ANCHOR',
  ...prefixFields('ORDER', commandOptionalFields),
  ...prefixFields('LAYER', commandOptionalFields),
  ...prefixFields('RENDER_MODE', commandOptionalFields),
  ...prefixFields('SHIFT_DISTANCE', commandValueFields),
  ...prefixFields('SHIFT_ANGLE', commandValueFields),
  ...prefixFields('SCALE', commandValueFields),
  ...prefixFields('OPACITY', commandValueFields),
  'BORDER_MODE',
  ...prefixFields('BORDER_WIDTH', commandOptionalFields),
  'BORDER_COLOR_HAS',
  ...commandBorderColorFields.map((field) => `BORDER_${field}`),
  'LEADERLINE_HAS',
  ...prefixFields('LEADERLINE_WIDTH', commandValueFields),
  ...commandLeaderlineColorFields,
  ...prefixFields('ANCHOR_X', commandValueFields),
  ...prefixFields('ANCHOR_Y', commandValueFields),
  ...prefixFields('ROTATION', commandRotationFields),
  ...prefixFields('AUTO_DIRECTION', commandAutoDirectionFields),
];

const commandPolylineNodeFields = ['X', 'Y', 'THICKNESS'];

const commandAddSpriteBaseFields = [
  'RESULT_INDEX',
  'ELEMENT_COUNT',
  ...prefixFields('SX', commandValueFields),
  ...prefixFields('SY', commandValueFields),
  ...prefixFields('SZ', commandOptionalFields),
  ...prefixFields('OPACITY', commandValueFields),
  ...prefixFields('VISIBILITY_DISTANCE', commandOptionalFields),
];

const commandAddPolylineBaseFields = [
  'RESULT_INDEX',
  'NODE_COUNT',
  ...prefixFields('LAYER', commandOptionalFields),
  ...prefixFields('OPACITY', commandValueFields),
  ...commandPolylineColorFields,
  ...commandPolylineJoinCorrectionFields,
  ...commandPolylineCapCorrectionFields,
];

const commandUpdateSpriteBaseFields = [
  'SPRITE_ID',
  'ISSUED_AT_TIMESTAMP',
  ...prefixFields('SX', commandValueFields),
  ...prefixFields('SY', commandValueFields),
  ...prefixFields('SZ', commandOptionalFields),
  ...prefixFields('OPACITY', commandValueFields),
  ...prefixFields('VISIBILITY_DISTANCE', commandOptionalFields),
  'ELEMENT_UPDATE_COUNT',
];

const commandUpdatePolylineBaseFields = [
  'POLYLINE_ID',
  'ISSUED_AT_TIMESTAMP',
  'NODE_COUNT',
  ...prefixFields('LAYER', commandOptionalFields),
  ...prefixFields('OPACITY', commandValueFields),
  'COLOR_HAS',
  ...commandPolylineColorFields,
  'JOIN_CORRECTION_HAS',
  ...commandPolylineJoinCorrectionFields,
  'CAP_CORRECTION_HAS',
  ...commandPolylineCapCorrectionFields,
];

const command = {
  bufferHeader: ['USED', 'COMMAND_COUNT'],
  commandHeader: ['OP', 'SIZE'],
  resultHeader: ['FAILED_COUNT', 'RESULT_COUNT'],
  commandOps: {
    UPDATE_CAMERA: 1,
    SET_TEXTURE_INFO: 2,
    ADD_SPRITE: 3,
    UPDATE_SPRITE: 4,
    REMOVE_SPRITE: 5,
    ADD_POLYLINE: 6,
    UPDATE_POLYLINE: 7,
    REMOVE_POLYLINE: 8,
    ADJUST_CAMERA_POSITION: 9,
    SET_TILED_TEXTURE_INFO: 10,
    SET_TEXTURE_TILE_INFO: 11,
  },
  enums: {
    imageMode: {
      KEEP: 0,
      CLEAR: 1,
      SET: 2,
    },
    borderMode: commandBorderMode,
    polylineCorrectionMode,
    elementKind: {
      NONE: 0,
      PRESENT: 1,
    },
    updateElementKind: {
      REMOVE: 0,
      UPDATE: 1,
    },
  },
  structs: {
    optional: commandOptionalFields,
    value: commandValueFields,
    rotation: commandRotationFields,
  },
  elementFields: commandElementFields,
  polylineNodeFields: commandPolylineNodeFields,
  polylineColorFields: commandPolylineColorFields,
  addSpriteBaseFields: commandAddSpriteBaseFields,
  addPolylineBaseFields: commandAddPolylineBaseFields,
  updateSpriteBaseFields: commandUpdateSpriteBaseFields,
  updatePolylineBaseFields: commandUpdatePolylineBaseFields,
  commands: {
    updateCamera: [
      ...prefixFields('POSITION_X', commandValueFields),
      ...prefixFields('POSITION_Y', commandValueFields),
      ...prefixFields('POSITION_Z', commandValueFields),
      ...prefixFields('ROTATION_YAW', commandValueFields),
      ...prefixFields('ROTATION_PITCH', commandValueFields),
      ...prefixFields('ROTATION_ROLL', commandValueFields),
      ...prefixFields('FOV_Y', commandValueFields),
      ...prefixFields('NEAR', commandOptionalFields),
      ...prefixFields('FAR', commandOptionalFields),
      ...prefixFields('VIEWPORT_ASPECT', commandOptionalFields),
    ],
    adjustCameraPosition: [
      ...prefixFields('PITCH', commandValueFields),
      ...prefixFields('FOV_Y', commandValueFields),
      ...prefixFields('NEAR', commandOptionalFields),
      ...prefixFields('FAR', commandOptionalFields),
      ...prefixFields('MOVE', commandValueFields),
    ],
    setTextureInfo: [
      'TEX_INDEX',
      'WIDTH',
      'HEIGHT',
      'VALID',
      'PAGE_ID',
      'U0',
      'V0',
      'U1',
      'V1',
    ],
    setTiledTextureInfo: [
      'TEX_INDEX',
      'WIDTH',
      'HEIGHT',
      'VALID',
      'TILE_COUNT',
    ],
    setTextureTileInfo: [
      'TEX_INDEX',
      'TILE_INDEX',
      'PAGE_ID',
      'U0',
      'V0',
      'U1',
      'V1',
      'LEFT_RATIO',
      'TOP_RATIO',
      'RIGHT_RATIO',
      'BOTTOM_RATIO',
    ],
  },
};

const wasmPolylineFields = [
  'OPACITY',
  'OPACITY_FROM',
  'OPACITY_TO',
  'OPACITY_PREV_TARGET',
  'OPACITY_START_TIMESTAMP',
  'OPACITY_DURATION',
  'OPACITY_CONFIG_DURATION',
  'OPACITY_MODE',
  'OPACITY_EASING',
  'OPACITY_EASING_PARAM0',
  'OPACITY_EASING_PARAM1',
  'OPACITY_EASING_PARAM2',
  'OPACITY_EASING_PARAM3',
  'LAYER',
  'COLOR0_R',
  'COLOR0_G',
  'COLOR0_B',
  'COLOR0_A',
  'COLOR1_R',
  'COLOR1_G',
  'COLOR1_B',
  'COLOR1_A',
  'REPEAT_LENGTH',
  'JOIN_CORRECTION_MODE',
  'JOIN_CORRECTION_INTERMEDIATE_POINT_COUNT',
  'CAP_CORRECTION_MODE',
  'CAP_CORRECTION_POINT_COUNT',
  'NODE_OFFSET',
  'NODE_COUNT',
];

const wasmPolylineNodeFields = ['X', 'Y', 'THICKNESS'];

const wasmStatePolylineFields = [
  'TIMESTAMP_MS',
  'OPACITY_VALUE',
  'OPACITY_HAS_INTERPOLATION',
  'OPACITY_FROM',
  'OPACITY_TO',
  'OPACITY_MODE',
  'OPACITY_DURATION',
  'OPACITY_EASING',
  'OPACITY_EASING_PARAM0',
  'OPACITY_EASING_PARAM1',
  'LAYER',
  'COLOR0_R',
  'COLOR0_G',
  'COLOR0_B',
  'COLOR0_A',
  'COLOR1_R',
  'COLOR1_G',
  'COLOR1_B',
  'COLOR1_A',
  'REPEAT_LENGTH',
  'JOIN_CORRECTION_MODE',
  'JOIN_CORRECTION_INTERMEDIATE_POINT_COUNT',
  'CAP_CORRECTION_MODE',
  'CAP_CORRECTION_POINT_COUNT',
  'NODE_COUNT',
];

const wasmDrawCommandHeaderFields = [
  'COMMAND_COUNT',
  'POLYLINE_VERTEX_COUNT',
  'SPRITE_OUTPUT_COUNT',
];
const wasmDrawCommandFields = ['KIND', 'START', 'COUNT', 'EXTRA'];

const wasm = {
  wasmOutputStride: 24,
  polylineOutputStride: 7,
  maxElementsPerSprite: 8,
  spriteFields: [
    'X',
    'X_FROM',
    'X_TO',
    'X_PREV_TARGET',
    'X_START_TIMESTAMP',
    'X_DURATION',
    'X_CONFIG_DURATION',
    'X_MODE',
    'X_EASING',
    'X_EASING_PARAM0',
    'X_EASING_PARAM1',
    'X_EASING_PARAM2',
    'X_EASING_PARAM3',
    'Y',
    'Y_FROM',
    'Y_TO',
    'Y_PREV_TARGET',
    'Y_START_TIMESTAMP',
    'Y_DURATION',
    'Y_CONFIG_DURATION',
    'Y_MODE',
    'Y_EASING',
    'Y_EASING_PARAM0',
    'Y_EASING_PARAM1',
    'Y_EASING_PARAM2',
    'Y_EASING_PARAM3',
    'PARENT_OPACITY',
    'PARENT_OPACITY_FROM',
    'PARENT_OPACITY_TO',
    'PARENT_OPACITY_PREV_TARGET',
    'PARENT_OPACITY_START_TIMESTAMP',
    'PARENT_OPACITY_DURATION',
    'PARENT_OPACITY_CONFIG_DURATION',
    'PARENT_OPACITY_MODE',
    'PARENT_OPACITY_EASING',
    'PARENT_OPACITY_EASING_PARAM0',
    'PARENT_OPACITY_EASING_PARAM1',
    'PARENT_OPACITY_EASING_PARAM2',
    'PARENT_OPACITY_EASING_PARAM3',
    'RENDER_OPACITY',
    'RENDER_OPACITY_FROM',
    'RENDER_OPACITY_TO',
    'RENDER_OPACITY_PREV_TARGET',
    'RENDER_OPACITY_START_TIMESTAMP',
    'RENDER_OPACITY_DURATION',
    'RENDER_OPACITY_CONFIG_DURATION',
    'RENDER_OPACITY_MODE',
    'RENDER_OPACITY_EASING',
    'RENDER_OPACITY_EASING_PARAM0',
    'RENDER_OPACITY_EASING_PARAM1',
    'RENDER_OPACITY_EASING_PARAM2',
    'RENDER_OPACITY_EASING_PARAM3',
    'VISIBILITY_DISTANCE',
    'LOD_VISIBLE',
    'Z',
  ],
  elementFields: [
    'WIDTH',
    'HEIGHT',
    'TEX_INDEX',
    'ORIGIN_LOCATION_SLOT',
    'ORIGIN_LOCATION_USE_RESOLVED_ANCHOR',
    'OWNER_SLOT',
    'ORDER',
    'LAYER',
    'RENDER_MODE',
    'OPACITY',
    'OPACITY_FROM',
    'OPACITY_TO',
    'OPACITY_PREV_TARGET',
    'OPACITY_START_TIMESTAMP',
    'OPACITY_DURATION',
    'OPACITY_CONFIG_DURATION',
    'OPACITY_MODE',
    'OPACITY_EASING',
    'OPACITY_EASING_PARAM0',
    'OPACITY_EASING_PARAM1',
    'OPACITY_EASING_PARAM2',
    'OPACITY_EASING_PARAM3',
    'RENDER_OPACITY',
    'RENDER_OPACITY_FROM',
    'RENDER_OPACITY_TO',
    'RENDER_OPACITY_PREV_TARGET',
    'RENDER_OPACITY_START_TIMESTAMP',
    'RENDER_OPACITY_DURATION',
    'RENDER_OPACITY_CONFIG_DURATION',
    'RENDER_OPACITY_MODE',
    'RENDER_OPACITY_EASING',
    'RENDER_OPACITY_EASING_PARAM0',
    'RENDER_OPACITY_EASING_PARAM1',
    'RENDER_OPACITY_EASING_PARAM2',
    'RENDER_OPACITY_EASING_PARAM3',
    'BORDER_WIDTH',
    'BORDER_COLOR_R',
    'BORDER_COLOR_G',
    'BORDER_COLOR_B',
    'BORDER_COLOR_A',
    'LEADERLINE_WIDTH',
    'LEADERLINE_WIDTH_FROM',
    'LEADERLINE_WIDTH_TO',
    'LEADERLINE_WIDTH_PREV_TARGET',
    'LEADERLINE_WIDTH_START_TIMESTAMP',
    'LEADERLINE_WIDTH_DURATION',
    'LEADERLINE_WIDTH_CONFIG_DURATION',
    'LEADERLINE_WIDTH_MODE',
    'LEADERLINE_WIDTH_EASING',
    'LEADERLINE_WIDTH_EASING_PARAM0',
    'LEADERLINE_WIDTH_EASING_PARAM1',
    'LEADERLINE_WIDTH_EASING_PARAM2',
    'LEADERLINE_WIDTH_EASING_PARAM3',
    'LEADERLINE_COLOR0_R',
    'LEADERLINE_COLOR0_G',
    'LEADERLINE_COLOR0_B',
    'LEADERLINE_COLOR0_A',
    'LEADERLINE_COLOR1_R',
    'LEADERLINE_COLOR1_G',
    'LEADERLINE_COLOR1_B',
    'LEADERLINE_COLOR1_A',
    'LEADERLINE_REPEAT_LENGTH',
    'ROTATE_DEG',
    'ROTATE_FROM',
    'ROTATE_TO',
    'ROTATE_PREV_TARGET',
    'ROTATE_START_TIMESTAMP',
    'ROTATE_DURATION',
    'ROTATE_CONFIG_DURATION',
    'ROTATE_MODE',
    'ROTATE_EASING',
    'ROTATE_EASING_PARAM0',
    'ROTATE_EASING_PARAM1',
    'ROTATE_EASING_PARAM2',
    'ROTATE_EASING_PARAM3',
    'SCALE',
    'SCALE_FROM',
    'SCALE_TO',
    'SCALE_PREV_TARGET',
    'SCALE_START_TIMESTAMP',
    'SCALE_DURATION',
    'SCALE_CONFIG_DURATION',
    'SCALE_MODE',
    'SCALE_EASING',
    'SCALE_EASING_PARAM0',
    'SCALE_EASING_PARAM1',
    'SCALE_EASING_PARAM2',
    'SCALE_EASING_PARAM3',
    'ANCHOR_X',
    'ANCHOR_X_FROM',
    'ANCHOR_X_TO',
    'ANCHOR_X_PREV_TARGET',
    'ANCHOR_X_START_TIMESTAMP',
    'ANCHOR_X_DURATION',
    'ANCHOR_X_CONFIG_DURATION',
    'ANCHOR_X_MODE',
    'ANCHOR_X_EASING',
    'ANCHOR_X_EASING_PARAM0',
    'ANCHOR_X_EASING_PARAM1',
    'ANCHOR_X_EASING_PARAM2',
    'ANCHOR_X_EASING_PARAM3',
    'ANCHOR_Y',
    'ANCHOR_Y_FROM',
    'ANCHOR_Y_TO',
    'ANCHOR_Y_PREV_TARGET',
    'ANCHOR_Y_START_TIMESTAMP',
    'ANCHOR_Y_DURATION',
    'ANCHOR_Y_CONFIG_DURATION',
    'ANCHOR_Y_MODE',
    'ANCHOR_Y_EASING',
    'ANCHOR_Y_EASING_PARAM0',
    'ANCHOR_Y_EASING_PARAM1',
    'ANCHOR_Y_EASING_PARAM2',
    'ANCHOR_Y_EASING_PARAM3',
    'SHIFT_DISTANCE',
    'SHIFT_DISTANCE_FROM',
    'SHIFT_DISTANCE_TO',
    'SHIFT_DISTANCE_PREV_TARGET',
    'SHIFT_DISTANCE_START_TIMESTAMP',
    'SHIFT_DISTANCE_DURATION',
    'SHIFT_DISTANCE_CONFIG_DURATION',
    'SHIFT_DISTANCE_MODE',
    'SHIFT_DISTANCE_EASING',
    'SHIFT_DISTANCE_EASING_PARAM0',
    'SHIFT_DISTANCE_EASING_PARAM1',
    'SHIFT_DISTANCE_EASING_PARAM2',
    'SHIFT_DISTANCE_EASING_PARAM3',
    'SHIFT_ANGLE_DEG',
    'SHIFT_ANGLE_DEG_FROM',
    'SHIFT_ANGLE_DEG_TO',
    'SHIFT_ANGLE_DEG_PREV_TARGET',
    'SHIFT_ANGLE_DEG_START_TIMESTAMP',
    'SHIFT_ANGLE_DEG_DURATION',
    'SHIFT_ANGLE_DEG_CONFIG_DURATION',
    'SHIFT_ANGLE_DEG_MODE',
    'SHIFT_ANGLE_DEG_EASING',
    'SHIFT_ANGLE_DEG_EASING_PARAM0',
    'SHIFT_ANGLE_DEG_EASING_PARAM1',
    'SHIFT_ANGLE_DEG_EASING_PARAM2',
    'SHIFT_ANGLE_DEG_EASING_PARAM3',
    'AUTO_DIRECTION_SPACE',
    'AUTO_DIRECTION_MODE',
    'AUTO_DIRECTION_SHIFT_ANGLE_ROTATION',
    'AUTO_DIRECTION_MIN_DISTANCE',
    'AUTO_DIRECTION_DEG',
    'AUTO_DIRECTION_PREV_PIVOT_X',
    'AUTO_DIRECTION_PREV_PIVOT_Y',
    'AUTO_DIRECTION_HAS_PREV',
    'AUTO_DIRECTION_FLIP_X_ENABLED',
    'AUTO_DIRECTION_FLIP_Y_ENABLED',
    'AUTO_DIRECTION_FLIP_INTERP_CONFIG_DURATION',
    'AUTO_DIRECTION_FLIP_INTERP_MODE',
    'AUTO_DIRECTION_FLIP_INTERP_EASING',
    'AUTO_DIRECTION_FLIP_INTERP_PARAM0',
    'AUTO_DIRECTION_FLIP_INTERP_PARAM1',
    'AUTO_DIRECTION_FLIP_INTERP_PARAM2',
    'AUTO_DIRECTION_FLIP_INTERP_PARAM3',
    'FINAL_ROTATE_DEG',
    'FINAL_ROTATE_FROM',
    'FINAL_ROTATE_TO',
    'FINAL_ROTATE_START_TIMESTAMP',
    'FINAL_ROTATE_DURATION',
    'FINAL_ROTATE_PREV_TARGET',
    'FINAL_ROTATE_CONFIG_DURATION',
    'FINAL_SHIFT_ANGLE_DEG',
    'FINAL_SHIFT_ANGLE_FROM',
    'FINAL_SHIFT_ANGLE_TO',
    'FINAL_SHIFT_ANGLE_START_TIMESTAMP',
    'FINAL_SHIFT_ANGLE_DURATION',
    'FINAL_SHIFT_ANGLE_PREV_TARGET',
    'FINAL_SHIFT_ANGLE_CONFIG_DURATION',
    'AUTO_FLIP_X',
    'AUTO_FLIP_X_FROM',
    'AUTO_FLIP_X_TO',
    'AUTO_FLIP_X_PREV_TARGET',
    'AUTO_FLIP_Y',
    'AUTO_FLIP_Y_FROM',
    'AUTO_FLIP_Y_TO',
    'AUTO_FLIP_Y_PREV_TARGET',
    'AUTO_FLIP_START_TIMESTAMP',
    'AUTO_FLIP_DURATION',
  ],
  stateSpriteFields: [
    'SX_VALUE',
    'SX_HAS_INTERPOLATION',
    'SX_FROM',
    'SX_TO',
    'SX_MODE',
    'SX_DURATION',
    'SX_EASING',
    'SX_EASING_PARAM0',
    'SX_EASING_PARAM1',
    'SY_VALUE',
    'SY_HAS_INTERPOLATION',
    'SY_FROM',
    'SY_TO',
    'SY_MODE',
    'SY_DURATION',
    'SY_EASING',
    'SY_EASING_PARAM0',
    'SY_EASING_PARAM1',
    'SZ',
    'OPACITY_VALUE',
    'OPACITY_HAS_INTERPOLATION',
    'OPACITY_FROM',
    'OPACITY_TO',
    'OPACITY_MODE',
    'OPACITY_DURATION',
    'OPACITY_EASING',
    'OPACITY_EASING_PARAM0',
    'OPACITY_EASING_PARAM1',
    'VISIBILITY_DISTANCE',
    'TIMESTAMP_MS',
    'VIEWPORT_BASE_VALID',
    'VIEWPORT_BASE_X_PIXEL',
    'VIEWPORT_BASE_Y_PIXEL',
  ],
  stateElementFields: [
    'SHIFT_DISTANCE_VALUE',
    'SHIFT_DISTANCE_HAS_INTERPOLATION',
    'SHIFT_DISTANCE_FROM',
    'SHIFT_DISTANCE_TO',
    'SHIFT_DISTANCE_MODE',
    'SHIFT_DISTANCE_DURATION',
    'SHIFT_DISTANCE_EASING',
    'SHIFT_DISTANCE_EASING_PARAM0',
    'SHIFT_DISTANCE_EASING_PARAM1',
    'SHIFT_ANGLE_DEG_VALUE',
    'SHIFT_ANGLE_DEG_HAS_INTERPOLATION',
    'SHIFT_ANGLE_DEG_FROM',
    'SHIFT_ANGLE_DEG_TO',
    'SHIFT_ANGLE_DEG_MODE',
    'SHIFT_ANGLE_DEG_DURATION',
    'SHIFT_ANGLE_DEG_EASING',
    'SHIFT_ANGLE_DEG_EASING_PARAM0',
    'SHIFT_ANGLE_DEG_EASING_PARAM1',
    'SCALE_VALUE',
    'SCALE_HAS_INTERPOLATION',
    'SCALE_FROM',
    'SCALE_TO',
    'SCALE_MODE',
    'SCALE_DURATION',
    'SCALE_EASING',
    'SCALE_EASING_PARAM0',
    'SCALE_EASING_PARAM1',
    'OPACITY_VALUE',
    'OPACITY_HAS_INTERPOLATION',
    'OPACITY_FROM',
    'OPACITY_TO',
    'OPACITY_MODE',
    'OPACITY_DURATION',
    'OPACITY_EASING',
    'OPACITY_EASING_PARAM0',
    'OPACITY_EASING_PARAM1',
    'BORDER_WIDTH',
    'BORDER_COLOR_R',
    'BORDER_COLOR_G',
    'BORDER_COLOR_B',
    'BORDER_COLOR_A',
    'LEADERLINE_WIDTH_VALUE',
    'LEADERLINE_WIDTH_HAS_INTERPOLATION',
    'LEADERLINE_WIDTH_FROM',
    'LEADERLINE_WIDTH_TO',
    'LEADERLINE_WIDTH_MODE',
    'LEADERLINE_WIDTH_DURATION',
    'LEADERLINE_WIDTH_EASING',
    'LEADERLINE_WIDTH_EASING_PARAM0',
    'LEADERLINE_WIDTH_EASING_PARAM1',
    'LEADERLINE_COLOR0_R',
    'LEADERLINE_COLOR0_G',
    'LEADERLINE_COLOR0_B',
    'LEADERLINE_COLOR0_A',
    'LEADERLINE_COLOR1_R',
    'LEADERLINE_COLOR1_G',
    'LEADERLINE_COLOR1_B',
    'LEADERLINE_COLOR1_A',
    'LEADERLINE_REPEAT_LENGTH',
    'ANCHOR_X_VALUE',
    'ANCHOR_X_HAS_INTERPOLATION',
    'ANCHOR_X_FROM',
    'ANCHOR_X_TO',
    'ANCHOR_X_MODE',
    'ANCHOR_X_DURATION',
    'ANCHOR_X_EASING',
    'ANCHOR_X_EASING_PARAM0',
    'ANCHOR_X_EASING_PARAM1',
    'ANCHOR_Y_VALUE',
    'ANCHOR_Y_HAS_INTERPOLATION',
    'ANCHOR_Y_FROM',
    'ANCHOR_Y_TO',
    'ANCHOR_Y_MODE',
    'ANCHOR_Y_DURATION',
    'ANCHOR_Y_EASING',
    'ANCHOR_Y_EASING_PARAM0',
    'ANCHOR_Y_EASING_PARAM1',
    'ROTATION_VALUE',
    'ROTATION_HAS_INTERPOLATION',
    'ROTATION_FROM',
    'ROTATION_TO',
    'ROTATION_MODE',
    'ROTATION_DURATION',
    'ROTATION_EASING',
    'ROTATION_EASING_PARAM0',
    'ROTATION_EASING_PARAM1',
    'AUTO_DIRECTION_SPACE',
    'AUTO_DIRECTION_MODE',
    'AUTO_DIRECTION_SHIFT_ANGLE_ROTATION',
    'AUTO_DIRECTION_MIN_DISTANCE',
    'AUTO_DIRECTION_DIRECTION_DEG',
    'AUTO_DIRECTION_FLIP_X_ENABLED',
    'AUTO_DIRECTION_FLIP_X_COMMAND_VALUE',
    'AUTO_DIRECTION_FLIP_X_VALUE',
    'AUTO_DIRECTION_FLIP_Y_ENABLED',
    'AUTO_DIRECTION_FLIP_Y_COMMAND_VALUE',
    'AUTO_DIRECTION_FLIP_Y_VALUE',
    'AUTO_DIRECTION_INTERP_HAS',
    'AUTO_DIRECTION_INTERP_MODE',
    'AUTO_DIRECTION_INTERP_DURATION',
    'AUTO_DIRECTION_INTERP_EASING',
    'AUTO_DIRECTION_INTERP_PARAM0',
    'AUTO_DIRECTION_INTERP_PARAM1',
    'ROTATION_FINAL_DEG',
    'SHIFT_ANGLE_FINAL_DEG',
    'ROTATION_START_TIMESTAMP',
    'ROTATION_T',
    'ROTATION_T_EASED',
    'ROTATION_DELTA_DEG',
    'FINAL_ROTATION_FROM',
    'FINAL_ROTATION_TO',
    'FINAL_ROTATION_START_TIMESTAMP',
    'FINAL_ROTATION_DURATION',
    'FINAL_ROTATION_T',
    'FINAL_ROTATION_T_EASED',
    'FINAL_ROTATION_DELTA_DEG',
    'TEX_INDEX',
    'ORIGIN_LOCATION_INDEX',
    'ORIGIN_LOCATION_USE_RESOLVED_ANCHOR',
    'ORDER',
    'LAYER',
    'RENDER_MODE',
  ],
  polylineFields: wasmPolylineFields,
  polylineNodeFields: wasmPolylineNodeFields,
  statePolylineFields: wasmStatePolylineFields,
  drawCommandHeaderFields: wasmDrawCommandHeaderFields,
  drawCommandFields: wasmDrawCommandFields,
  drawCommandKinds: {
    SPRITE: 0,
    POLYLINE: 1,
  },
  cameraFields: [
    'PROJECTION_DIRTY',
    'POSITION_X',
    'POSITION_Y',
    'POSITION_Z',
    'ROTATION_YAW',
    'ROTATION_PITCH',
    'ROTATION_ROLL',
    'FOV_Y',
    'NEAR',
    'FAR',
    'VIEWPORT_ASPECT',
    'SPRITE_SCALING_MIN_DISTANCE',
    'SPRITE_SCALING_MAX_DISTANCE',
    'POLYLINE_SCALING_MIN_DISTANCE',
    'POLYLINE_SCALING_MAX_DISTANCE',
    'POSITION_X_FROM',
    'POSITION_X_TO',
    'POSITION_X_START_TIMESTAMP',
    'POSITION_X_DURATION',
    'POSITION_X_CONFIG_DURATION',
    'POSITION_X_MODE',
    'POSITION_X_EASING',
    'POSITION_X_EASING_PARAM0',
    'POSITION_X_EASING_PARAM1',
    'POSITION_X_EASING_PARAM2',
    'POSITION_X_EASING_PARAM3',
    'POSITION_X_PREV_TARGET',
    'POSITION_Y_FROM',
    'POSITION_Y_TO',
    'POSITION_Y_START_TIMESTAMP',
    'POSITION_Y_DURATION',
    'POSITION_Y_CONFIG_DURATION',
    'POSITION_Y_MODE',
    'POSITION_Y_EASING',
    'POSITION_Y_EASING_PARAM0',
    'POSITION_Y_EASING_PARAM1',
    'POSITION_Y_EASING_PARAM2',
    'POSITION_Y_EASING_PARAM3',
    'POSITION_Y_PREV_TARGET',
    'POSITION_Z_FROM',
    'POSITION_Z_TO',
    'POSITION_Z_START_TIMESTAMP',
    'POSITION_Z_DURATION',
    'POSITION_Z_CONFIG_DURATION',
    'POSITION_Z_MODE',
    'POSITION_Z_EASING',
    'POSITION_Z_EASING_PARAM0',
    'POSITION_Z_EASING_PARAM1',
    'POSITION_Z_EASING_PARAM2',
    'POSITION_Z_EASING_PARAM3',
    'POSITION_Z_PREV_TARGET',
    'ROTATION_YAW_FROM',
    'ROTATION_YAW_TO',
    'ROTATION_YAW_START_TIMESTAMP',
    'ROTATION_YAW_DURATION',
    'ROTATION_YAW_CONFIG_DURATION',
    'ROTATION_YAW_MODE',
    'ROTATION_YAW_EASING',
    'ROTATION_YAW_EASING_PARAM0',
    'ROTATION_YAW_EASING_PARAM1',
    'ROTATION_YAW_EASING_PARAM2',
    'ROTATION_YAW_EASING_PARAM3',
    'ROTATION_YAW_PREV_TARGET',
    'ROTATION_PITCH_FROM',
    'ROTATION_PITCH_TO',
    'ROTATION_PITCH_START_TIMESTAMP',
    'ROTATION_PITCH_DURATION',
    'ROTATION_PITCH_CONFIG_DURATION',
    'ROTATION_PITCH_MODE',
    'ROTATION_PITCH_EASING',
    'ROTATION_PITCH_EASING_PARAM0',
    'ROTATION_PITCH_EASING_PARAM1',
    'ROTATION_PITCH_EASING_PARAM2',
    'ROTATION_PITCH_EASING_PARAM3',
    'ROTATION_PITCH_PREV_TARGET',
    'ROTATION_ROLL_FROM',
    'ROTATION_ROLL_TO',
    'ROTATION_ROLL_START_TIMESTAMP',
    'ROTATION_ROLL_DURATION',
    'ROTATION_ROLL_CONFIG_DURATION',
    'ROTATION_ROLL_MODE',
    'ROTATION_ROLL_EASING',
    'ROTATION_ROLL_EASING_PARAM0',
    'ROTATION_ROLL_EASING_PARAM1',
    'ROTATION_ROLL_EASING_PARAM2',
    'ROTATION_ROLL_EASING_PARAM3',
    'ROTATION_ROLL_PREV_TARGET',
    'FOV_Y_FROM',
    'FOV_Y_TO',
    'FOV_Y_START_TIMESTAMP',
    'FOV_Y_DURATION',
    'FOV_Y_CONFIG_DURATION',
    'FOV_Y_MODE',
    'FOV_Y_EASING',
    'FOV_Y_EASING_PARAM0',
    'FOV_Y_EASING_PARAM1',
    'FOV_Y_EASING_PARAM2',
    'FOV_Y_EASING_PARAM3',
    'FOV_Y_PREV_TARGET',
    'POSITION_X_HAS_INTERPOLATION',
    'POSITION_Y_HAS_INTERPOLATION',
    'POSITION_Z_HAS_INTERPOLATION',
    'ROTATION_YAW_HAS_INTERPOLATION',
    'ROTATION_PITCH_HAS_INTERPOLATION',
    'ROTATION_ROLL_HAS_INTERPOLATION',
    'FOV_Y_HAS_INTERPOLATION',
  ],
  applyStatsFields: ['TOTAL_MS', 'LOOP_MS', 'SYNC_SLOTS_MS', 'CLEAR_MS'],
  computeStatsFields: [
    'TOTAL_MS',
    'PROJECTION_MS',
    'SPRITE_ANIMATION_MS',
    'ELEMENT_ANIMATION_MS',
    'PIVOT_RESOLVE_MS',
    'AUTO_ROTATION_MS',
    'CAMERA_TRACKING_MS',
    'COLLECT_ENTRIES_MS',
    'SORT_ENTRIES_MS',
    'WRITE_OUTPUT_MS',
    'ELEMENT_ANIMATION_OWNER_MS',
    'ELEMENT_ANIMATION_OPACITY_MS',
    'ELEMENT_ANIMATION_ROTATION_MS',
    'ELEMENT_ANIMATION_SCALE_MS',
    'ELEMENT_ANIMATION_ANCHOR_MS',
    'ELEMENT_ANIMATION_SHIFT_MS',
    'ELEMENT_ANIMATION_PIVOT_MS',
    'ELEMENT_ANIMATION_MERGE_MS',
    'ELEMENT_ANIMATION_SCALAR_MS',
    'ELEMENT_ANIMATION_SIMD_LOOP_MS',
    'CAMERA_TRACKING_APPLIED',
    'CAMERA_TRACKING_RESOLVED_DISTANCE',
    'CAMERA_DIRTY',
  ],
  interpolation: {
    modeFeedback: 0,
    modeFeedforward: 1,
    easingLinear: 0,
    easingSigmoid: 1,
    easingEase: 2,
    easingExponential: 3,
    easingQuadratic: 4,
    easingCubic: 5,
    easingSine: 6,
    easingBounce: 7,
    easingBack: 8,
  },
  common: {
    renderMode: {
      surface: 0,
      billboard: 1,
      billboardPerspective: 2,
    },
    autoDirectionMode,
    autoDirectionSpace,
    polylineCorrectionMode,
    cameraTracking: {
      targetMode: {
        base: 0,
        contentApprox: 1,
      },
      interpolationKind: {
        keep: 0,
        clear: 1,
        set: 2,
      },
      defaults: {
        fitPadding: 1.1,
        fitZoomBias: 1.0,
      },
    },
    defaultCamera: {
      fovY: 45.0,
      near: 0.1,
      far: 10000.0,
    },
    expApprox: {
      scale: 12102203,
      bias: 1064866805,
      clamp: 10,
    },
  },
};

module.exports = {
  command,
  wasm,
};
